-- DATA VIEWING PURPOSES
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPT2;
SELECT * FROM POSITIONS;
SELECT * FROM ALLOWANCE;
SELECT * FROM POS_ALL;
SELECT * FROM PROJ;
SELECT * FROM GRADE;
SELECT * FROM EMP_PHONE;
SELECT * FROM LOGIN;
SELECT * FROM TRANSACTIONS;
SELECT * FROM VEHICLE;
SELECT * FROM OVERTIME;

-- INITIALIZATION
DROP TABLE OVERTIME;
DROP TABLE VEHICLE;
DROP TABLE TRANSACTIONS;
DROP TABLE ASSIGNED_TO;
DROP TABLE LOGIN;
DROP TABLE EMP_PHONE;
DROP TABLE GRADE;
DROP TABLE PROJ;
DROP TABLE EMPLOYEE;
DROP TABLE DEPT2;
DROP TABLE POS_ALL;
DROP TABLE ALLOWANCE;
DROP TABLE POSITIONS;

-- TABLE CREATION   
CREATE TABLE DEPT2 
(DNAME VARCHAR2(15), DESC_ VARCHAR2(25) NOT NULL,
CONSTRAINT DEPT_DNAME PRIMARY KEY (DNAME));

CREATE TABLE GRADE 
(GRADE_TYPE VARCHAR2(1), MINSAL NUMBER (5), MAXSAL NUMBER(5), HOURLY_PAY NUMBER(4),
CONSTRAINT GRADE_GRADE_TYPE PRIMARY KEY (GRADE_TYPE));

CREATE TABLE ALLOWANCE
(ALLOWANCE_TYPE VARCHAR2(15), AM0UNT NUMBER(5) NOT NULL,
CONSTRAINT ALL_ATYPE PRIMARY KEY (ALLOWANCE_TYPE));

CREATE TABLE POSITIONS
(POSITION_TYPE VARCHAR2(10), CONSTRAINT POS_PTYPE PRIMARY KEY (POSITION_TYPE));

CREATE TABLE POS_ALL
(POSITION_TYPE VARCHAR2(10), ALLOWANCE_TYPE VARCHAR2(15),
CONSTRAINT PA_PRIM PRIMARY KEY (POSITION_TYPE, ALLOWANCE_TYPE), CONSTRAINT A_FK FOREIGN KEY (ALLOWANCE_TYPE) REFERENCES ALLOWANCE(ALLOWANCE_TYPE),
CONSTRAINT P_FK FOREIGN KEY (POSITION_TYPE) REFERENCES POSITIONS(POSITION_TYPE));

CREATE TABLE EMPLOYEE (
EMP_ID NUMBER(3), ENAME VARCHAR2(40) NOT NULL, POSITION_TYPE VARCHAR2(10), GENDER VARCHAR2(1),
SALARY NUMBER(5), DOB DATE NOT NULL, HIREDATE DATE NOT NULL, COMM NUMBER(5), DNAME VARCHAR2(15),
NOW_DATE DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT EMPLOYEE_EMP_ID PRIMARY KEY (EMP_ID), CONSTRAINT EMPLOYEE_GENDER_CK CHECK (GENDER IN ('M', 'F')),
CONSTRAINT EMPLOYEE_DNAME_FK FOREIGN KEY (DNAME) REFERENCES DEPT2(DNAME), CONSTRAINT EMPLOYEE_PTYPE_FK FOREIGN KEY (POSITION_TYPE) REFERENCES POSITIONS(POSITION_TYPE),
CONSTRAINT EMPLOYEE_AGE CHECK (TRUNC(MONTHS_BETWEEN(NOW_DATE, DOB) / 12) BETWEEN 18 AND 60));

CREATE TABLE PROJ
(PROJ_ID NUMBER(3), PNAME VARCHAR2(15) NOT NULL, PDESC VARCHAR2(200),
CONSTRAINT PROJ_PROJECT_ID PRIMARY KEY (PROJ_ID));

CREATE TABLE ASSIGNED_TO
(DNAME VARCHAR2(15) NOT NULL REFERENCES DEPT2(DNAME), PROJ_ID NUMBER(3) NOT NULL REFERENCES PROJ(PROJ_ID), CONSTRAINT ASSIGNED_TO_PRIMARY PRIMARY KEY (DNAME, PROJ_ID));

CREATE TABLE EMP_PHONE
(EMP_ID NUMBER(3), PHONE NUMBER(8) NOT NULL,
CONSTRAINT EP_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID), CONSTRAINT EP_PRIMARY PRIMARY KEY (EMP_ID, PHONE));

CREATE TABLE LOGIN
(USERNAME VARCHAR2(20), USERPASS VARCHAR2(50) NOT NULL, EMP_ID NUMBER(3) UNIQUE, SESHINFO VARCHAR2(50),
CONSTRAINT LOGIN_PRIMARY PRIMARY KEY (USERNAME), CONSTRAINT LOGIN_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID));

CREATE TABLE TRANSACTIONS 
(TRANSACTION_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP(6), USERNAME VARCHAR2(20), EMP_ID NUMBER(3), 
POSITION_TYPE VARCHAR2(10),
CONSTRAINT T_PRIMARY PRIMARY KEY (TRANSACTION_TIMESTAMP, USERNAME, EMP_ID));

CREATE TABLE VEHICLE (
VEHICLE_ID NUMBER(6), NEXT_M_DATE DATE NOT NULL, V_MODEL VARCHAR2(15) NOT NULL,
MAKE VARCHAR2(15) NOT NULL, EMP_ID NUMBER(3) UNIQUE, NOW_DATE DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT MNT_DATE_CK CHECK ((NEXT_M_DATE > ADD_MONTHS(NOW_DATE, 3)) AND (NEXT_M_DATE < ADD_MONTHS(NOW_DATE, 6))),
CONSTRAINT V_VEHICLE_ID PRIMARY KEY (VEHICLE_ID),
CONSTRAINT V_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID));

CREATE TABLE OVERTIME 
(OVERTIME_ID NUMBER(3), WORKING_HOURS NUMBER(2), SHIFT VARCHAR2(5), EMP_ID NUMBER(3), OVERTIME_DATE DATE NOT NULL, 
CONSTRAINT O_OVT_ID PRIMARY KEY (OVERTIME_ID), CONSTRAINT O_SHIFT_CK CHECK (SHIFT='DAY' OR SHIFT='NIGHT'),
CONSTRAINT O_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID), CONSTRAINT O_WORKING_HOURS_CK CHECK (WORKING_HOURS <= 8));


--SAMPLE DATA...................................................................
INSERT INTO DEPT2 VALUES ('RESEARCH','Researchers');
INSERT INTO DEPT2 VALUES ('REPAIRS','Repairs Personnel');
INSERT INTO DEPT2 VALUES ('IT','IT Personnel');
INSERT INTO DEPT2 VALUES ('TECH','Technicians');
INSERT INTO DEPT2 VALUES ('ECONOMICS','Economists');

INSERT INTO GRADE VALUES ('A',15000,99999,100);
INSERT INTO GRADE VALUES ('B',10000,14999,80);
INSERT INTO GRADE VALUES ('C',5000,9999,60);
INSERT INTO GRADE VALUES ('D',3000,4999,40);
INSERT INTO GRADE VALUES ('E',0,2999,20);

INSERT INTO ALLOWANCE VALUES ('SOCIAL',2000);
INSERT INTO ALLOWANCE VALUES ('UNIFORM',1500);
INSERT INTO ALLOWANCE VALUES ('HOUSE',5000);
INSERT INTO ALLOWANCE VALUES ('MANAGER',8000);
INSERT INTO ALLOWANCE VALUES ('FUEL',500);

INSERT INTO POSITIONS VALUES ('MANAGER');
INSERT INTO POSITIONS VALUES ('ACCOUNTANT');
INSERT INTO POSITIONS VALUES ('ADMIN');
INSERT INTO POSITIONS VALUES ('CLERK');
INSERT INTO POSITIONS VALUES ('HR');

INSERT INTO POS_ALL VALUES ('MANAGER','FUEL');
INSERT INTO POS_ALL VALUES ('MANAGER','HOUSE');
INSERT INTO POS_ALL VALUES ('MANAGER','SOCIAL');
INSERT INTO POS_ALL VALUES ('MANAGER','MANAGER');
INSERT INTO POS_ALL VALUES ('ACCOUNTANT','SOCIAL');
INSERT INTO POS_ALL VALUES ('ADMIN','HOUSE');
INSERT INTO POS_ALL VALUES ('ADMIN','SOCIAL');
INSERT INTO POS_ALL VALUES ('CLERK','SOCIAL');
INSERT INTO POS_ALL VALUES ('CLERK','UNIFORM');
INSERT INTO POS_ALL VALUES ('HR','SOCIAL');
INSERT INTO POS_ALL VALUES ('HR','UNIFORM');

INSERT INTO PROJ VALUES (101,'PROJ1','Research on new technology');
INSERT INTO PROJ VALUES (102,'PROJ2','Scale IT department');
INSERT INTO PROJ VALUES (103,'PROJ3','Repairing');
INSERT INTO PROJ VALUES (104,'PROJ4','Updating inventory');
INSERT INTO PROJ VALUES (105,'PROJ5', null);

INSERT INTO ASSIGNED_TO VALUES ('RESEARCH',101);
INSERT INTO ASSIGNED_TO VALUES ('IT',102);
INSERT INTO ASSIGNED_TO VALUES ('REPAIRS',103);
INSERT INTO ASSIGNED_TO VALUES ('TECH',103);
INSERT INTO ASSIGNED_TO VALUES ('REPAIRS',104);
INSERT INTO ASSIGNED_TO VALUES ('IT',105);

INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (111, 'John Roger', 'MANAGER','M',15000,'04-FEB-2002','19-FEB-2023', 3000,'IT');
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (222, 'Samuel Miguel','ACCOUNTANT','M',15400,'16-MAR-2003','13-MAR-2023', 0,'ECONOMICS');
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (333, 'Sarah Johnson','HR','F',13000,'26-JUN-2002','11-DEC-2022', 500,'RESEARCH');
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (444, 'Aisha Suleyman','CLERK','M',10000,'14-AUG-1980', '23-JAN-2023',NULL,'TECH');
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (555, 'Harris Brown','CLERK','F',11000,'19-FEB-2000', '8-NOV-2022',NULL,'REPAIRS');
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (666, 'Roxas Sora','ADMIN','M',12000,'04-FEB-2002','19-FEB-2023', 2000,'IT');
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (777, 'Rii Sora','HR','F',9000,'04-FEB-2002','19-FEB-2023', NULL,'REPAIRS');
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (888, 'Roxas Rii','ADMIN','M',2300,'04-FEB-2002','19-FEB-2023', 1250,'TECH');
INSERT INTO EMPLOYEE (EMP_ID,ENAME, POSITION_TYPE, GENDER, SALARY, DOB, HIREDATE, COMM, DNAME) VALUES (999, 'Rii Roxas','HR','F',23000,'04-FEB-2002','19-FEB-2023', NULL,'RESEARCH');

INSERT INTO EMP_PHONE VALUES (111,'11112222');
INSERT INTO EMP_PHONE VALUES (111,'22223333');
INSERT INTO EMP_PHONE VALUES (222,'11223344');
INSERT INTO EMP_PHONE VALUES (333,'12345678');
INSERT INTO EMP_PHONE VALUES (444,'91011121');
INSERT INTO EMP_PHONE VALUES (444,'13141516');
INSERT INTO EMP_PHONE VALUES (555,'17181920');
INSERT INTO EMP_PHONE VALUES (666,'21212121');
INSERT INTO EMP_PHONE VALUES (777,'31313131');
INSERT INTO EMP_PHONE VALUES (888,'41414141');
INSERT INTO EMP_PHONE VALUES (999,'51515151');

INSERT INTO LOGIN (USERNAME, USERPASS, EMP_ID) VALUES ('grub','789ghi',333);
INSERT INTO LOGIN (USERNAME, USERPASS, EMP_ID) VALUES ('jones','123456wewew',999);
INSERT INTO LOGIN (USERNAME, USERPASS, EMP_ID) VALUES ('bones','34780zzz',777);


INSERT INTO TRANSACTIONS (USERNAME, EMP_ID, POSITION_TYPE) VALUES ('jones',999,'HR');
INSERT INTO TRANSACTIONS (USERNAME, EMP_ID, POSITION_TYPE) VALUES ('grub',333,'HR');
INSERT INTO TRANSACTIONS (USERNAME, EMP_ID, POSITION_TYPE) VALUES ('bones',777,'HR');


INSERT INTO VEHICLE (VEHICLE_ID, NEXT_M_DATE, V_MODEL, MAKE, EMP_ID) VALUES (111111, '05-SEP-2023', 'Toyota', 'Corolla', 111);
INSERT INTO VEHICLE (VEHICLE_ID, NEXT_M_DATE, V_MODEL, MAKE, EMP_ID) VALUES (160305,'12-SEP-2023','CHARGER','DODGE',222);
INSERT INTO VEHICLE (VEHICLE_ID, NEXT_M_DATE, V_MODEL, MAKE, EMP_ID) VALUES (123456,'25-SEP-2023','GAL','LAMBO',333);
INSERT INTO VEHICLE (VEHICLE_ID, NEXT_M_DATE, V_MODEL, MAKE, EMP_ID) VALUES (345678,'28-AUG-2023','SUNNY','NISSAN',444);
INSERT INTO VEHICLE (VEHICLE_ID, NEXT_M_DATE, V_MODEL, MAKE, EMP_ID) VALUES (998876,'04-OCT-2023','CAMRY','TOYOTA',555);

INSERT INTO OVERTIME VALUES (100,7,'NIGHT',111,'08-MAY-2023');
INSERT INTO OVERTIME VALUES (110,8,'NIGHT',222,'07-MAY-2023');
INSERT INTO OVERTIME VALUES (120,6,'NIGHT',333,'08-MAY-2023');
INSERT INTO OVERTIME VALUES (130,3,'DAY',444,'09-MAY-2023');
INSERT INTO OVERTIME VALUES (140,1,'DAY',555,'05-MAY-2023');

commit;